version: "3.9"

volumes:
  database:
    external: false

services:
  api:
    container_name: app-api
    restart: alawys
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: app-mysql
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=112233
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: alawys
  ##  mongo
  # db:
  #   container_name: app-mongo
  #   image: "mongo:latest"
  #   volumes:
  #     - database:/data/db
  #   ports:
  #     - "27017:27017"
  #   restart: alawys

networks:
  default:
    external: false
    # Use a custom driver
    driver: bridge
    name: app-network-bridge
